/**
 * Creates a dedicated Neon TEST database for the auth integration suite and
 * generates services/auth/.env.test pointing at it.
 *
 * Usage (from anywhere in the repo):
 *   node services/auth/scripts/create-test-db.cjs
 *
 * Reads AUTH_POSTGRES_DATABASE_URL from the repo root .env (the dev link).
 * The TEST link it produces is a different database — langphy_auth_test — on
 * the same Neon project, so the suite never touches dev data. Idempotent.
 *
 * If your Neon role cannot run CREATE DATABASE, create the database in the
 * Neon dashboard and add AUTH_TEST_POSTGRES_DATABASE_URL manually to
 * services/auth/.env.test.
 */
const fs = require("fs");
const path = require("path");
const { Client } = require("pg");

const SERVICES_AUTH_DIR = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(SERVICES_AUTH_DIR, "..", "..");
const DEV_ENV_FILE = path.join(REPO_ROOT, ".env");
const TEST_ENV_FILE = path.join(SERVICES_AUTH_DIR, ".env.test");
const TEST_DB = process.env.AUTH_TEST_DATABASE_NAME || "langphy_auth_test";

function loadDotEnv(file) {
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = /^\s*([A-Z_]+)\s*=\s*(.*)$/.exec(line);
    if (m) out[m[1]] = m[2].trim();
  }
  return out;
}

async function main() {
  const devEnv = loadDotEnv(DEV_ENV_FILE);
  const devUrl = (devEnv.AUTH_POSTGRES_DATABASE_URL || devEnv.POSTGRES_DATABASE_URL || "").trim();
  if (!devUrl) {
    console.error(`[create-test-db] No AUTH_POSTGRES_DATABASE_URL found in ${DEV_ENV_FILE}`);
    process.exit(1);
  }

  const url = new URL(devUrl);
  const devDb = url.pathname.split("/").filter(Boolean).pop() || "postgres";

  const client = new Client({
    connectionString: devUrl,
    ssl: { rejectUnauthorized: false },
  });
  try {
    await client.connect();
    const exists = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [TEST_DB]
    );
    if (exists.rowCount === 0) {
      await client.query(`CREATE DATABASE "${TEST_DB}"`);
      console.log(`[create-test-db] created database "${TEST_DB}" (same Neon project as "${devDb}")`);
    } else {
      console.log(`[create-test-db] database "${TEST_DB}" already exists`);
    }
  } catch (err) {
    console.error(`[create-test-db] could not create "${TEST_DB}": ${err.message}`);
    console.error("  → Create a database named " + TEST_DB + " in the Neon dashboard, then set");
    console.error("    AUTH_TEST_POSTGRES_DATABASE_URL=<connection-string> in " + TEST_ENV_FILE);
    process.exit(1);
  } finally {
    await client.end().catch(() => {});
  }

  url.pathname = `/${TEST_DB}`;
  const testUrl = url.toString();

  fs.writeFileSync(
    TEST_ENV_FILE,
    `# Generated by services/auth/scripts/create-test-db.cjs — DO NOT COMMIT (gitignored).\n` +
    `# Points the auth integration suite at a dedicated Neon TEST database.\n` +
    `# Tables are truncated between runs; never point this at a dev/prod DB.\n` +
    `AUTH_TEST_POSTGRES_DATABASE_URL=${testUrl}\n`,
    "utf8"
  );
  console.log(`[create-test-db] wrote ${TEST_ENV_FILE} (gitignored)`);
  console.log("[create-test-db] done — run `cd services/auth && npm test`");
}

main();